config/routes.rb
Rails.application.routes.draw do
  resources :purchases, :except => [:edit, :update]
  resources :discounts, :except => [:show]
  resources :customers
  resources :products

  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :destroy]

  def index
    @purchases = Purchase.all
  end


  def show
  end


  def new
    @purchase = Purchase.new
    @customers = Customer.all.map {|customer| [customer.name, customer.id]}
    @products = Product.all
    @discounts = Discount.all
  end


  def create
    @purchase = Purchase.create(purchase_params)
    @purchase.place_a_purchase(products_params_value)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to purchases_path, notice: 'purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :index }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'purchase was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_purchase
      @purchase = Purchase.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:customer_id)
    end

    def products_params_value
      params.require(:purchase).permit(products: [:id, :quantity])[:products]
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
	<% if @purchase.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

			<ul>
			<% @purchase.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :customer_id, "Apply to Customer:" %><br>
		<%= f.select :customer_id, @customers.nil? ? [@purchase.customer.name, @purchase.customer_id] : @customers %>
	</div>
	<br>

	<% @products.each do |product| %>
	<div class="field">
		<label><%= product.name %> with quantity: </label>
		<%= hidden_field_tag("purchase[products][][id]", nil, value: "#{product.id}", class: "form-control") %>
		<%= number_field_tag("purchase[products][][quantity]", nil, min: 0, value: 0, class: "form-control") %>
	</div>
	<br>
	<% end %>

	<br>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/purchases/index.html.erb
<h1>Purchases List</h1>

<p id="notice"><%= notice %></p>
<table>
	<tr>
		<th>Purchase ID</th>
		<th>Purchase Customer Name</th>
		<th>Purchase Products</th>
		<th>Purchase Total</th>
		<th>Purchase Price ($)</th>
		<th colspan="3">Available Actions</th>
	</tr>

	<% if !@purchases.blank? %>
		<% @purchases.each do |purchase| %>
			<tr>
				<td><%= purchase.id %></td>
				<td><%= purchase.customer.name.blank? ?  "Unnamed" : purchase.customer.name %></td>
				<td><%= purchase.products.all.map { |product| product.name }.join(", ") %></td>
				<td><%= purchase.total %></td>
				<td><%= link_to 'Show', purchase %></td>
				<td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	<% end %>

	<tr>
		<td><%= link_to "new purchase", new_purchase_path %></td>
		<td colspan="6">to create new purchase</td>
	</tr>
</table>

app/views/purchases/new.html.erb
<h1>Create New Purchase</h1>

<% if @customers.blank? %>
	<h2> No customer profile </h2>
	Create <%= link_to 'one', new_customer_path %>?
<% elsif @products.blank? %>
	<h2> No product available! </h2>
	Create <%= link_to 'one', new_product_path %>?
<% elsif @discounts.blank? %>
	<h2> No discounts available! App won't work without one active discount.</h2>
	Create <%= link_to 'one', new_discount_path %>?
<% else %>
	<%= render 'form' %>
<% end %>

<br>
<%= link_to 'Back', products_path %>

app/views/purchases/show.html.erb
<h1>Purchase Details</h1>

<% if !@purchase.blank? %>
<table>
	<tr>
			<td colspan="4">Product ID:</td>
			<td><%= @purchase.id %></td>
	</tr>

	<tr>
			<td colspan="4">Customer Name:</td>
			<td><%= @purchase.customer.name %></td>
	</tr>

	<tr>
		<td colspan="5"><hr></td>
	</tr>

	<tr>
			<td>Products</td>
			<td>Original Price</td>
			<td>Discount Applied</td>
			<td>Discount Rate</td>
			<td>Total</td>
	</tr>

	<% @purchase.products_purchases.all.each do |purchased_product| %>
		<% product = purchased_product.product %>
		<% discount = Discount.find_by(id: purchased_product.discount_id) %>

		<tr>
				<td><%= product.name %></td>
				<td><%= product.price %></td>
				<td><%= discount.blank? ? "-" : DiscountsHelper::DISCOUNT_TYPE.key(discount.discount_type) %></td>
				<td><%= discount.blank? ? "N/A" : discount.rate %></td>
				<td><%= purchased_product.charged %></td>
		</tr>
	<% end %>

	<tr>
		<td colspan="5"><hr></td>
	</tr>

	<tr>
		<td colspan="4">Total (USD): </td>
		<td><%= @purchase.total %></td>
	</tr>

	<tr>
		<td colspan="5"><hr></td>
	</tr>

	<tr>
		<td colspan="3"><%= link_to 'Delete This Purchase', @purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td colspan="2"><%= link_to "Back to List", purchases_path %></td>
	</tr>
</table>
<% else %>
<h2>Can't find the user. Action?</h2>
<table>
	<tr>
		<td><%= link_to 'Select A Purchase', purchases_path %></td>
		<td><%= link_to "Create New Purchase", new_purchase_path %></td>
	</tr>
</table>
<% end %>