config/routes.rb
Rails.application.routes.draw do
  resources :purchases, :except => [:edit, :update]
  resources :discounts, :except => [:show]
  resources :customers
  resources :products

  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :product
  belongs_to :customer
  has_many :products_purchases

  validates :product_id, presence: true
  validates :customer_id, presence: true
  validates :discount_type, presence: true
  validates :minimum_purchase, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :rate, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]
  before_action :get_helper_datas, only: [:new, :show, :edit, :update, :destroy]

  def index
    @discounts = Discount.all
  end


  def new
    @discount = Discount.new
    @products = Product.all.map { |product| [product.name, product.id] }
    @customers = Customer.all.map { |customer| [customer.name, customer.id] }
  end


  def create
    @discount = Discount.new(discount_params)
    respond_to do |format|
      if @discount.save
        format.html { redirect_to discounts_path, notice: 'discount was successfully created.' }
        format.json { render :nothing => true, :status => 204 }
      else
        @products = Product.all.map { |product| [product.name, product.id] }
        @customers = Customer.all.map { |customer| [customer.name, customer.id] }
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @discount_type = DiscountsHelper::DISCOUNT_TYPE.map { |discount_type| discount_type }
    @status = DiscountsHelper::DISCOUNT_STATUS.map { |discount_status| discount_status }
    product = @discount.product
    @products = [[product.name, product.id]]
    customer = @discount.customer
    @customers = [[customer.name, customer.id]]
  end


  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discounts_path, notice: 'discount was successfully updated.' }
        format.json { render :nothing => true, :status => 204 }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'discount was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_discount
      @discount = Discount.find_by(id: params[:id])
    end

    def get_helper_datas
      @discount_type = DiscountsHelper::DISCOUNT_TYPE.map { |discount_type| discount_type }
      @status = DiscountsHelper::DISCOUNT_STATUS.map { |discount_status| discount_status }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:product_id, :customer_id, :discount_type, :rate, :status, :minimum_purchase)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper

DISCOUNT_TYPE = { "price reduction (%)" => 0,
                  "free item reduction (units)" => 1
                }

DISCOUNT_STATUS = { "inactive" => 0,
                    "active" => 1
                  }


end

app/views/discounts/_form.html.erb
<%= form_for(@discount) do |f| %>
	<% if @discount.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

			<ul>
			<% @discount.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :product_id, "Apply to Product:" %><br>
		<%= f.select :product_id, @products %>
	</div>
	<br>

	<div class="field">
		<%= f.label :customer_id, "Apply to Customer:" %><br>
		<%= f.select :customer_id, @customers %>
	</div>
	<br>

	<div class="field">
		<%= f.label :discount_type %><br>
		<%= f.select :discount_type, @discount_type %>
	</div>
	<br>


	<div class="field">
		<%= f.label :minimum_purchase, "Minimum Purchase: (e.g '10' = buy 10 get this discount)"%><br>
		<%= f.number_field :minimum_purchase, min: 0, value: 0, placeholder: "E.g 10" %>
	</div>
	<br>


	<div class="field">
		<%= f.label :rate, "Rate: (e.g '10' for 10\% or get 10 units free)"%><br>
		<%= f.number_field :rate, min: 0, value: "0.00000", step: 'any', placeholder: "E.g 10" %>
	</div>
	<br>

	<div class="field">
		<%= f.label :status, "Set Discount Status to:"%><br>
		<%= f.select :status, @status %>
	</div>
	<br>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount Details</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<h1>Discounts List</h1>

<p id="notice"><%= notice %></p>

<table>
	<tr>
		<th>Discount ID</th>
		<th>Applied To Product</th>
		<th>Applied To Customer</th>
		<th>Minimum Purchase</th>
		<th>Discount Type</th>
		<th>Discount Rate</th>
		<th>Current Status</th>
		<th colspan="2">Available Actions</th>
	</tr>

	<% if !@discounts.blank? %>
		<% @discounts.each do |discount| %>
			<tr>
				<td><%= discount.id %></td>
				<td><%= discount.product.blank? ?  "No product applied." : discount.product.name %></td>
				<td><%= discount.customer.blank? ?  "Does Not belongs to any user." : discount.customer.name %></td>
				<td><%= discount.minimum_purchase %>
				<td><%= discount.discount_type.blank? ?  "Unknown Type" : DiscountsHelper::DISCOUNT_TYPE.key(discount.discount_type) %></td>
				<td><%= discount.rate == 0 ? "0" : discount.rate %></td>
				<td><%= DiscountsHelper::DISCOUNT_STATUS.key(discount.status) %></td>
				<td><%= link_to 'Edit', edit_discount_path(discount) %></td>
				<td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	<% end %>

	<tr>
		<td><%= link_to "new discount", new_discount_path %></td>
		<td colspan="8">to create new discount</td>
	</tr>
</table>

app/views/discounts/new.html.erb
<h1>Create New Discount</h1>

<% if @customers.blank? %>
	<h2> No customer profile </h2>
	Create <%= link_to 'one', new_customer_path %>?
<% elsif @products.blank? %>
	<h2> No product available! </h2>
	Create <%= link_to 'one', new_product_path %>?
<% else %>
	<%= render 'form' %>
<% end %>

<br>
<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>