config/routes.rb
Rails.application.routes.draw do
  resources :purchases, :except => [:edit, :update]
  resources :discounts, :except => [:show]
  resources :customers
  resources :products

  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :discounts
  has_many :product_purchases
  has_many :purchases, through: :product_purchases

  validates :name, presence: true
  validates :product_type, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end


  def show
  end


  def new
    @product = Product.new
  end


  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end


  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'product was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :product_type, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
			<% @product.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :product_type %><br>
		<%= f.text_field :product_type %>
	</div>

	<div class="field">
		<%= f.label :price, "Price ($USD):" %><br>
		<%= f.text_field :price, :placeholder => (number_with_precision(0.00, :precision => 2) || 0) %>
	</div>

	<br>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product Details</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products List</h1>

<p id="notice"><%= notice %></p>

<table>
	<tr>
		<th>Product ID</th>
		<th>Product Name</th>
		<th>Product Type</th>
		<th>Product Price ($)</th>
		<th colspan="3">Available Actions</th>
	</tr>

	<% if !@products.blank? %>
		<% @products.each do |product| %>
			<tr>
				<td><%= product.id %></td>
				<td><%= product.name.blank? ?  "Unnamed" : product.name %></td>
				<td><%= product.product_type.blank? ?  "Unknown Product Type" : product.product_type %></td>
				<td><%= product.price.blank? ?  "Unknown Price" : product.price %></td>
				<td><%= link_to 'Show', product %></td>
				<td><%= link_to 'Edit', edit_product_path(product) %></td>
				<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	<% end %>

	<tr>
		<td><%= link_to "new product", new_product_path %></td>
		<td colspan="6">to create new product</td>
	</tr>
</table>

app/views/products/new.html.erb
<h1>Create New Product</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product Details</h1>

<% if !@product.blank? %>
<table>
	<tr>
		<th>Product ID</th>
		<th>Product Name</th>
		<th>Product Type</th>
		<th>Product Price ($)</th>
	</tr>
	<tr>
			<td><%= @product.id %></td>
			<td><%= @product.name.blank? ?  "Unnamed" : @product.name %></td>
			<td><%= @product.product_type.blank? ?  "Unknown Product Type" : @product.product_type %></td>
			<td><%= @product.price.blank? ?  "Unknown Price" : @product.price %></td>
	</tr>
	<tr>
		<td><%= link_to 'Edit Details', edit_product_path(@product) %></td>
		<td><%= link_to 'Delete This Product', @product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td colspan="2"><%= link_to "Back to List", products_path %></td>
	</tr>
</table>
<% else %>
<h2>Can't find the user. Action?</h2>
<table>
	<tr>
		<td><%= link_to 'Select A Product', products_path %></td>
		<td><%= link_to "Create New Product", new_product_path %></td>
	</tr>
</table>
<% end %>